version: '3'

services:
  backend:
    image: spaicer/digital-coil-backend
  frontend:
    image: spaicer/digital-coil
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - 8080:80
